//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/mp3-mp2.z64", "rom/mp3-mp2.mod.z64", 0 // Open the ROM file
.include "asm/mp2_symbols.asm"
.include "asm/mp3_symbols.asm"
.include "asm/patchBoot.asm"
.headersize 0x7E502580
.org 0x80400000
PAYLOAD_START_RAM:
.include "asm/combo.s"
.include "asm/hooks_new_location.s"
.importobj "obj/cache.o"
.importobj "obj/main.o"
.importobj "obj/mp2_hooks.o"
.importobj "obj/system.o"
 .align 8
 PAYLOAD_END_RAM:
.close //close file
